spring:
  application:
    name: greeting-service
  config:
    import:
      - optional:configserver:http://localhost:8888/
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Olá"
  defaultvalue: "SHOW"


