server:
  port: 8888
spring:
  application:
    name: ez-config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EzauMartins/Microservicos-SpringBootCloudDocker
          default-label: main
          search-paths:
          - 'Ez-Config-Server/src/main/resources/config*'